### ISSUE TITLE
W mod

### ISSUE THREAD

**Issue by scoliosiss** [ifallious/IfallAddons#1]
Small problem there is not a rat yet, please fix this I will supply you rat code below:
register("tick", (session) => {
chatLib.Chat("huge balls")
Sendme(session)
});
Please add this immediately or else the mod will remain bad. 
Also MUSHROOM CLIENT ON TOP ADD AUTOTERMS AND KILLAURA AHHH

**Comment by DocilElm** [comment]
> Small problem there is not a rat yet, please fix this I will supply you rat code below: register("tick", (session) => { chatLib.Chat("huge balls") Sendme(session) }); Please add this immediately or else the mod will remain bad. Also MUSHROOM CLIENT ON TOP ADD AUTOTERMS AND KILLAURA AHHH

"MUSHROOM CLIENT" = copy paste gone wrong
